[package]
name = "tcp-leak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.3.0"
actix-http= "3.0.0-beta.10"
actix-web = {version="4.0.0-beta.9", features=["rustls"]}
structopt = "0.3.23"
tokio = "1"
rustls = "0.19.1"